name: media_player
description: "A comprehensive media player package for LMS platforms with video, audio, and document support. Includes offline playback, progress tracking, and state management agnostic design."
version: 0.0.1

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Video player
  media_kit: ^1.2.1
  media_kit_video: ^1.3.1
  media_kit_libs_video: ^1.0.7

  # Audio player
  just_audio: ^0.10.5
  audio_service: ^0.18.18
  audio_session: ^0.2.2

  # Document Viewer
  syncfusion_flutter_pdfviewer: ^31.2.10
  file_picker: ^10.3.6
  open_filex: ^4.7.0

  # Storage
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5

  http: ^1.6.0

  # Utilities
  path: ^1.9.1
  uuid: ^4.5.2
  rxdart: ^0.28.0
  equatable: ^2.0.7
  meta: ^1.16.0
  # cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner:
  mockito:
